create or replace function public.executive_dashboard_metrics(p_days_back integer default 30)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v jsonb; v_org uuid; start_at timestamptz;
begin
 if not public.has_permission('dashboard.view') then raise exception 'not authorized'; end if;
 v_org:=public.current_organization_id(); start_at:=now()-make_interval(days=>greatest(p_days_back,1));
 select jsonb_build_object(
 'period_days',greatest(p_days_back,1),
 'commercial',jsonb_build_object('leads',coalesce((select count(*) from leads where organization_id=v_org and created_at>=start_at),0),'appointments',coalesce((select count(*) from appointments where organization_id=v_org and created_at>=start_at),0),'open_proposals',coalesce((select count(*) from proposals where organization_id=v_org and status in ('draft','sent','countered','accepted')),0),'won_deals',coalesce((select count(*) from deals where organization_id=v_org and status='completed' and coalesce(completed_at,created_at)>=start_at),0),'won_value',coalesce((select sum(sale_value) from deals where organization_id=v_org and status='completed' and coalesce(completed_at,created_at)>=start_at),0),'commission_receivable',coalesce((select sum(greatest(coalesce(commission_value,0)-coalesce(commission_received_amount,0),0)) from deals where organization_id=v_org and status<>'cancelled' and created_at>=start_at),0)),
 'rentals',case when public.has_permission('rentals.view') then jsonb_build_object('active_contracts',(select count(*) from rental_contracts where organization_id=v_org and status in ('active','ending')),'monthly_rent',(select coalesce(sum(monthly_rent),0) from rental_contracts where organization_id=v_org and status in ('active','ending')),'overdue_value',(select coalesce(sum(greatest(total_due-paid_amount,0)),0) from rental_payments where organization_id=v_org and status in ('pending','partial','overdue') and due_date<current_date),'expiring_60_days',(select count(*) from rental_contracts where organization_id=v_org and status in ('active','ending') and end_date between current_date and current_date+60),'open_maintenance',(select count(*) from rental_maintenance where organization_id=v_org and status in ('open','in_progress','waiting'))) else '{}'::jsonb end,
 'finance',case when public.has_permission('financial.view') then jsonb_build_object('income_paid',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='income' and status='paid' and coalesce(paid_at,due_date::timestamptz,created_at)>=start_at),'expense_paid',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='expense' and status='paid' and coalesce(paid_at,due_date::timestamptz,created_at)>=start_at),'receivable',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='income' and status='pending'),'payable',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='expense' and status='pending'),'overdue_receivable',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='income' and status='pending' and due_date<current_date),'overdue_payable',(select coalesce(sum(amount),0) from finance_entries where organization_id=v_org and managed_funds=false and direction='expense' and status='pending' and due_date<current_date)) else '{}'::jsonb end
 ) into v; return v;
end $$;
revoke all on function public.executive_dashboard_metrics(integer) from public,anon; grant execute on function public.executive_dashboard_metrics(integer) to authenticated;