alter table public.appointments add constraint appointments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.appointments add constraint appointments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.appointments add constraint appointments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.appointments add constraint appointments_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.capture_documents add constraint capture_documents_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES owner_captures(id) ON DELETE CASCADE;
alter table public.capture_notes add constraint capture_notes_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES owner_captures(id) ON DELETE CASCADE;
alter table public.capture_notes add constraint capture_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.capture_status_history add constraint capture_status_history_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES owner_captures(id) ON DELETE CASCADE;
alter table public.capture_status_history add constraint capture_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_capture_document_id_fkey FOREIGN KEY (capture_document_id) REFERENCES capture_documents(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES owner_captures(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_deal_document_id_fkey FOREIGN KEY (deal_document_id) REFERENCES deal_documents(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_property_document_id_fkey FOREIGN KEY (property_document_id) REFERENCES property_documents(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_rental_contract_id_fkey FOREIGN KEY (rental_contract_id) REFERENCES rental_contracts(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_rental_document_id_fkey FOREIGN KEY (rental_document_id) REFERENCES rental_documents(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_rental_tenant_id_fkey FOREIGN KEY (rental_tenant_id) REFERENCES rental_tenants(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.crm_documents add constraint crm_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.crm_monthly_goals add constraint crm_monthly_goals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.crm_monthly_goals add constraint crm_monthly_goals_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.deal_documents add constraint deal_documents_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table public.deal_status_history add constraint deal_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.deal_status_history add constraint deal_status_history_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table public.deals add constraint deals_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.deals add constraint deals_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.deals add constraint deals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.deals add constraint deals_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.deals add constraint deals_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.deals add constraint deals_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE SET NULL;
alter table public.lead_notes add constraint lead_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_notes add constraint lead_notes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_preferences add constraint lead_preferences_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_preferences add constraint lead_preferences_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_preferences add constraint lead_preferences_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_property_matches add constraint lead_property_matches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_property_matches add constraint lead_property_matches_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_property_matches add constraint lead_property_matches_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.lead_property_matches add constraint lead_property_matches_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_source_history add constraint lead_source_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.lead_status_history add constraint lead_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.lead_status_history add constraint lead_status_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.leads add constraint leads_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.leads add constraint leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.leads add constraint leads_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.neighborhoods add constraint neighborhoods_city_id_fkey FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE RESTRICT;
alter table public.organization_members add constraint organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_members add constraint organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_members add constraint organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.owner_captures add constraint owner_captures_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.owner_captures add constraint owner_captures_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.owner_captures add constraint owner_captures_converted_property_id_fkey FOREIGN KEY (converted_property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.properties add constraint properties_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.properties add constraint properties_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.properties add constraint properties_city_id_fkey FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE RESTRICT;
alter table public.properties add constraint properties_neighborhood_id_fkey FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE RESTRICT;
alter table public.property_documents add constraint property_documents_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.property_features add constraint property_features_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE;
alter table public.property_features add constraint property_features_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.property_images add constraint property_images_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.property_management add constraint property_management_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.property_management add constraint property_management_source_capture_id_fkey FOREIGN KEY (source_capture_id) REFERENCES owner_captures(id) ON DELETE SET NULL;
alter table public.property_price_history add constraint property_price_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.property_price_history add constraint property_price_history_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.property_status_history add constraint property_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.property_status_history add constraint property_status_history_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.proposal_status_history add constraint proposal_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.proposal_status_history add constraint proposal_status_history_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE CASCADE;
alter table public.proposals add constraint proposals_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.proposals add constraint proposals_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.proposals add constraint proposals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.proposals add constraint proposals_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.proposals add constraint proposals_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.rental_adjustments add constraint rental_adjustments_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_adjustments add constraint rental_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_adjustments add constraint rental_adjustments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_cases add constraint rental_cases_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.rental_cases add constraint rental_cases_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.rental_charges add constraint rental_charges_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_charges add constraint rental_charges_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_collection_actions add constraint rental_collection_actions_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES rental_charges(id) ON DELETE CASCADE;
alter table public.rental_collection_actions add constraint rental_collection_actions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_collection_actions add constraint rental_collection_actions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_contract_tenants add constraint rental_contract_tenants_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_contract_tenants add constraint rental_contract_tenants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_contract_tenants add constraint rental_contract_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES rental_tenants(id) ON DELETE RESTRICT;
alter table public.rental_contracts add constraint rental_contracts_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.rental_contracts add constraint rental_contracts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.rental_contracts add constraint rental_contracts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.rental_contracts add constraint rental_contracts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_contracts add constraint rental_contracts_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT;
alter table public.rental_documents add constraint rental_documents_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_documents add constraint rental_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_guarantees add constraint rental_guarantees_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_guarantees add constraint rental_guarantees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_inspections add constraint rental_inspections_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_inspections add constraint rental_inspections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_inspections add constraint rental_inspections_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.rental_maintenance add constraint rental_maintenance_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_maintenance add constraint rental_maintenance_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_maintenance add constraint rental_maintenance_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.rental_payments add constraint rental_payments_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_payments add constraint rental_payments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_process_tenants add constraint rental_process_tenants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_process_tenants add constraint rental_process_tenants_process_id_fkey FOREIGN KEY (process_id) REFERENCES rental_processes(id) ON DELETE CASCADE;
alter table public.rental_process_tenants add constraint rental_process_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES rental_tenants(id) ON DELETE CASCADE;
alter table public.rental_processes add constraint rental_processes_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_processes add constraint rental_processes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_processes add constraint rental_processes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.rental_processes add constraint rental_processes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_processes add constraint rental_processes_primary_tenant_id_fkey FOREIGN KEY (primary_tenant_id) REFERENCES rental_tenants(id) ON DELETE SET NULL;
alter table public.rental_processes add constraint rental_processes_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.rental_stage_history add constraint rental_stage_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_stage_history add constraint rental_stage_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.rental_stage_history add constraint rental_stage_history_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
alter table public.rental_stage_history add constraint rental_stage_history_rental_case_id_fkey FOREIGN KEY (rental_case_id) REFERENCES rental_cases(id) ON DELETE CASCADE;
alter table public.rental_status_history add constraint rental_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.rental_status_history add constraint rental_status_history_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_status_history add constraint rental_status_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_tenants add constraint rental_tenants_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rental_tenants add constraint rental_tenants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rental_transfers add constraint rental_transfers_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES rental_charges(id) ON DELETE CASCADE;
alter table public.rental_transfers add constraint rental_transfers_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES rental_contracts(id) ON DELETE CASCADE;
alter table public.rental_transfers add constraint rental_transfers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.site_events add constraint site_events_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.site_visits add constraint site_visits_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE SET NULL;
alter table public.social_messages add constraint social_messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.team_activity_log add constraint team_activity_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.team_activity_log add constraint team_activity_log_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;;
