CREATE UNIQUE INDEX neighborhoods_city_slug_unique ON public.neighborhoods USING btree (city_id, slug);
CREATE INDEX owner_captures_created_at_idx ON public.owner_captures USING btree (created_at DESC);
CREATE INDEX owner_captures_next_action_idx ON public.owner_captures USING btree (next_action_at);
CREATE INDEX owner_captures_property_idx ON public.owner_captures USING btree (converted_property_id);
CREATE INDEX owner_captures_status_idx ON public.owner_captures USING btree (status);
CREATE INDEX properties_city_idx ON public.properties USING btree (city_id);
CREATE INDEX properties_created_at_idx ON public.properties USING btree (created_at DESC);
CREATE INDEX properties_featured_idx ON public.properties USING btree (featured);
CREATE INDEX properties_neighborhood_idx ON public.properties USING btree (neighborhood_id);
CREATE INDEX properties_purpose_idx ON public.properties USING btree (purpose);
CREATE INDEX properties_rent_price_idx ON public.properties USING btree (rent_price);
CREATE INDEX properties_sale_price_idx ON public.properties USING btree (sale_price);
CREATE INDEX properties_status_idx ON public.properties USING btree (status);
CREATE INDEX properties_type_idx ON public.properties USING btree (property_type);
CREATE INDEX property_documents_property_idx ON public.property_documents USING btree (property_id, display_order);
CREATE UNIQUE INDEX property_images_one_cover ON public.property_images USING btree (property_id) WHERE (is_cover = true);
CREATE INDEX property_images_property_idx ON public.property_images USING btree (property_id, display_order);
CREATE INDEX property_management_authorization_idx ON public.property_management USING btree (authorization_status, authorization_expires_at);
CREATE INDEX property_management_exclusivity_idx ON public.property_management USING btree (exclusivity, exclusivity_until);
CREATE INDEX property_management_review_idx ON public.property_management USING btree (next_review_at);
CREATE INDEX property_price_history_property_idx ON public.property_price_history USING btree (property_id, created_at DESC);
CREATE INDEX property_status_history_property_idx ON public.property_status_history USING btree (property_id, created_at DESC);
CREATE INDEX proposal_status_history_proposal_idx ON public.proposal_status_history USING btree (proposal_id, created_at DESC);
CREATE INDEX proposals_lead_idx ON public.proposals USING btree (lead_id);
CREATE INDEX proposals_next_follow_up_idx ON public.proposals USING btree (next_follow_up_at);
CREATE INDEX proposals_property_idx ON public.proposals USING btree (property_id);
CREATE INDEX proposals_status_idx ON public.proposals USING btree (status);
CREATE INDEX proposals_valid_until_idx ON public.proposals USING btree (valid_until);
CREATE INDEX rental_adjustments_contract_idx ON public.rental_adjustments USING btree (contract_id, effective_date DESC);
CREATE INDEX rental_cases_lead_idx ON public.rental_cases USING btree (lead_id);
CREATE INDEX rental_cases_stage_entered_idx ON public.rental_cases USING btree (stage_entered_at);
CREATE INDEX rental_cases_stage_idx ON public.rental_cases USING btree (stage, active);
CREATE INDEX rental_charges_contract_month_idx ON public.rental_charges USING btree (contract_id, reference_month);
CREATE INDEX rental_charges_org_due_idx ON public.rental_charges USING btree (organization_id, status, due_date);
CREATE INDEX rental_collection_actions_charge_idx ON public.rental_collection_actions USING btree (charge_id, contacted_at DESC);
CREATE UNIQUE INDEX rental_contract_one_primary_idx ON public.rental_contract_tenants USING btree (contract_id) WHERE (role = 'primary'::text);
CREATE INDEX rental_contracts_assigned_idx ON public.rental_contracts USING btree (assigned_to, status);
CREATE INDEX rental_contracts_lead_idx ON public.rental_contracts USING btree (lead_id);
CREATE UNIQUE INDEX rental_contracts_one_active_property_idx ON public.rental_contracts USING btree (property_id) WHERE (status = ANY (ARRAY['active'::text, 'renewal'::text, 'ending'::text]));
CREATE INDEX rental_contracts_org_status_idx ON public.rental_contracts USING btree (organization_id, status, end_date);
CREATE INDEX rental_contracts_property_idx ON public.rental_contracts USING btree (property_id, status);
CREATE INDEX rental_documents_contract_idx ON public.rental_documents USING btree (contract_id, party, display_order);
CREATE INDEX rental_inspections_contract_idx ON public.rental_inspections USING btree (contract_id, created_at DESC);
CREATE INDEX rental_inspections_org_schedule_idx ON public.rental_inspections USING btree (organization_id, status, scheduled_at);
CREATE INDEX rental_maintenance_contract_idx ON public.rental_maintenance USING btree (contract_id, created_at DESC);
CREATE INDEX rental_maintenance_org_status_idx ON public.rental_maintenance USING btree (organization_id, status, due_at);
CREATE INDEX rental_payments_contract_idx ON public.rental_payments USING btree (contract_id, reference_month);
CREATE INDEX rental_payments_org_due_idx ON public.rental_payments USING btree (organization_id, due_date, status);
CREATE UNIQUE INDEX rental_process_one_primary_idx ON public.rental_process_tenants USING btree (process_id) WHERE (responsibility = 'primary'::text);
CREATE INDEX rental_processes_org_stage_idx ON public.rental_processes USING btree (organization_id, stage, updated_at DESC);
CREATE INDEX rental_processes_property_idx ON public.rental_processes USING btree (property_id, stage);
CREATE INDEX rental_stage_history_case_idx ON public.rental_stage_history USING btree (rental_case_id, created_at DESC);
CREATE INDEX rental_stage_history_property_idx ON public.rental_stage_history USING btree (property_id, created_at DESC);
CREATE INDEX rental_status_history_contract_idx ON public.rental_status_history USING btree (contract_id, created_at DESC);
CREATE UNIQUE INDEX rental_tenants_org_cpf_unique ON public.rental_tenants USING btree (organization_id, regexp_replace(COALESCE(cpf, ''::text), '[^0-9]'::text, ''::text, 'g'::text)) WHERE ((cpf IS NOT NULL) AND (btrim(cpf) <> ''::text));
CREATE INDEX rental_tenants_org_name_idx ON public.rental_tenants USING btree (organization_id, full_name);
CREATE INDEX rental_transfers_org_status_idx ON public.rental_transfers USING btree (organization_id, status, due_date);
CREATE INDEX site_events_created_at_idx ON public.site_events USING btree (created_at DESC);
CREATE INDEX site_events_property_idx ON public.site_events USING btree (property_id);
CREATE INDEX site_events_type_idx ON public.site_events USING btree (event_type);
CREATE INDEX site_visits_created_at_idx ON public.site_visits USING btree (created_at DESC);
CREATE INDEX site_visits_property_idx ON public.site_visits USING btree (property_id);
CREATE INDEX site_visits_session_idx ON public.site_visits USING btree (session_id);
CREATE UNIQUE INDEX social_messages_external_message_unique ON public.social_messages USING btree (platform, external_message_id);
CREATE INDEX social_messages_lead_idx ON public.social_messages USING btree (lead_id, created_at DESC);
CREATE INDEX social_messages_platform_lead_idx ON public.social_messages USING btree (platform, lead_id, created_at DESC);
CREATE INDEX social_messages_unread_idx ON public.social_messages USING btree (lead_id, read_at) WHERE (direction = 'inbound'::text);
CREATE INDEX team_activity_log_org_created_idx ON public.team_activity_log USING btree (organization_id, created_at DESC);;
