CREATE OR REPLACE FUNCTION public.ensure_rental_contract_code()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if new.code is null or trim(new.code)='' then new.code:='LOC-'||lpad(nextval('public.rental_contract_code_seq')::text,4,'0'); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.track_rental_status_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if tg_op='INSERT' then insert into public.rental_status_history(organization_id,contract_id,from_status,to_status,changed_by) values(new.organization_id,new.id,null,new.status,auth.uid()); elsif old.status is distinct from new.status then insert into public.rental_status_history(organization_id,contract_id,from_status,to_status,changed_by) values(new.organization_id,new.id,old.status,new.status,auth.uid()); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.sync_rental_property_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_purpose text; begin select purpose into v_purpose from public.properties where id=new.property_id; if v_purpose='rent' then if new.status='awaiting_signature' then update public.properties set status='reserved' where id=new.property_id and status<>'reserved'; elsif new.status in('active','ending') then update public.properties set status='rented' where id=new.property_id and status<>'rented'; elsif new.status in('ended','cancelled') then update public.properties set status='published' where id=new.property_id and status in('reserved','rented'); end if; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.apply_rental_payment_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin new.total_due:=greatest(coalesce(new.rent_amount,0)+coalesce(new.condominium_amount,0)+coalesce(new.property_tax_amount,0)+coalesce(new.other_charges,0)-coalesce(new.discount_amount,0),0); if new.status<>'waived' then if coalesce(new.paid_amount,0)>=new.total_due and new.total_due>0 then new.status:='paid'; new.paid_at:=coalesce(new.paid_at,now()); elsif coalesce(new.paid_amount,0)>0 then new.status:='partial'; elsif new.due_date<current_date then new.status:='overdue'; new.paid_at:=null; else new.status:='pending'; new.paid_at:=null; end if; end if; if new.status='waived' then new.owner_net_amount:=0; elsif new.status='paid' then new.owner_net_amount:=greatest(coalesce(new.paid_amount,0)-coalesce(new.management_fee,0),0); else new.owner_net_amount:=greatest(coalesce(new.paid_amount,0)-least(coalesce(new.management_fee,0),coalesce(new.paid_amount,0)),0); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.generate_rental_payment_schedule(p_contract_id uuid)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare c public.rental_contracts%rowtype; m date; v_count integer:=0; v_tax numeric(14,2); v_fee numeric(14,2); begin if not public.has_permission('rentals.manage') then raise exception 'Sem permissão para gerenciar locações.'; end if; select * into c from public.rental_contracts where id=p_contract_id and organization_id=public.current_organization_id(); if not found then raise exception 'Contrato não encontrado.'; end if; if c.start_date is null or c.end_date is null or c.monthly_rent is null then raise exception 'Informe início, fim e valor mensal antes de gerar cobranças.'; end if; v_tax:=case when c.property_tax_payer='tenant' then coalesce(c.property_tax_amount,0) else 0 end; v_fee:=round(coalesce(c.monthly_rent,0)*coalesce(c.administration_fee_percent,0)/100.0,2); for m in select gs::date from generate_series(date_trunc('month',c.start_date)::date,date_trunc('month',c.end_date)::date,interval '1 month') gs loop insert into public.rental_payments(organization_id,contract_id,reference_month,due_date,rent_amount,condominium_amount,property_tax_amount,management_fee) values(c.organization_id,c.id,m,least(greatest((m+(c.due_day-1)*interval '1 day')::date,c.start_date),c.end_date),coalesce(c.monthly_rent,0),coalesce(c.condominium_amount,0),v_tax,v_fee) on conflict(contract_id,reference_month) do update set due_date=excluded.due_date,rent_amount=excluded.rent_amount,condominium_amount=excluded.condominium_amount,property_tax_amount=excluded.property_tax_amount,management_fee=excluded.management_fee,updated_at=now() where public.rental_payments.status in('pending','overdue') and coalesce(public.rental_payments.paid_amount,0)=0; v_count:=v_count+1; end loop; return v_count; end; $function$;

CREATE OR REPLACE FUNCTION public.refresh_rental_payment_statuses()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_count integer; begin if not public.has_permission('rentals.view') then return 0; end if; update public.rental_payments set status=case when status='waived' then 'waived' when paid_amount>=total_due and total_due>0 then 'paid' when paid_amount>0 then 'partial' when due_date<current_date then 'overdue' else 'pending' end,updated_at=now() where organization_id=public.current_organization_id() and status not in('waived','paid'); get diagnostics v_count=row_count; return v_count; end; $function$;

CREATE OR REPLACE FUNCTION public.apply_rental_document_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if new.status in('received','validated') and old.status is distinct from new.status then new.received_at:=coalesce(new.received_at,now()); end if; if new.status='validated' and old.status is distinct from 'validated' then new.validated_at:=coalesce(new.validated_at,now()); elsif new.status<>'validated' then new.validated_at:=null; end if; if new.status='pending' then new.received_at:=null; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.seed_rental_documents()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin insert into public.rental_documents(organization_id,contract_id,doc_key,label,party,display_order) values(new.organization_id,new.id,'tenant_id','Documento de identificação do locatário','tenant',10),(new.organization_id,new.id,'income_proof','Comprovante de renda','tenant',20),(new.organization_id,new.id,'residence_proof','Comprovante de residência','tenant',30),(new.organization_id,new.id,'guarantee','Documento da garantia locatícia','guarantee',40),(new.organization_id,new.id,'signed_contract','Contrato de locação assinado','contract',50),(new.organization_id,new.id,'entry_inspection','Laudo de vistoria de entrada','inspection',60) on conflict(contract_id,doc_key) do nothing; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.rental_dashboard_metrics()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$ with org as(select public.current_organization_id() id),contracts as(select * from public.rental_contracts where organization_id=(select id from org)),payments as(select * from public.rental_payments where organization_id=(select id from org)),maint as(select * from public.rental_maintenance where organization_id=(select id from org)) select case when public.has_permission('rentals.view') then jsonb_build_object('active_contracts',(select count(*) from contracts where status in('active','ending')),'monthly_rent',(select coalesce(sum(monthly_rent),0) from contracts where status in('active','ending')),'monthly_management_fee',(select coalesce(sum(coalesce(monthly_rent,0)*coalesce(administration_fee_percent,0)/100.0),0) from contracts where status in('active','ending')),'due_this_month',(select coalesce(sum(total_due),0) from payments where date_trunc('month',reference_month)=date_trunc('month',current_date)),'received_this_month',(select coalesce(sum(paid_amount),0) from payments where date_trunc('month',reference_month)=date_trunc('month',current_date)),'overdue_count',(select count(*) from payments where status in('pending','partial','overdue') and due_date<current_date and status<>'waived'),'overdue_value',(select coalesce(sum(greatest(total_due-paid_amount,0)),0) from payments where status in('pending','partial','overdue') and due_date<current_date),'expiring_60_days',(select count(*) from contracts where status in('active','ending') and end_date between current_date and current_date+60),'open_maintenance',(select count(*) from maint where status in('open','in_progress','waiting'))) else '{}'::jsonb end; $function$;;
