alter table public.agency_public_settings add constraint agency_public_settings_pkey PRIMARY KEY (id);
alter table public.appointments add constraint appointments_pkey PRIMARY KEY (id);
alter table public.capture_documents add constraint capture_documents_pkey PRIMARY KEY (id);
alter table public.capture_documents add constraint capture_documents_capture_id_document_type_key UNIQUE (capture_id, document_type);
alter table public.capture_notes add constraint capture_notes_pkey PRIMARY KEY (id);
alter table public.capture_status_history add constraint capture_status_history_pkey PRIMARY KEY (id);
alter table public.cities add constraint cities_pkey PRIMARY KEY (id);
alter table public.cities add constraint cities_slug_key UNIQUE (slug);
alter table public.crm_documents add constraint crm_documents_pkey PRIMARY KEY (id);
alter table public.crm_documents add constraint crm_documents_storage_path_key UNIQUE (storage_path);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_pkey PRIMARY KEY (id);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_period_month_key UNIQUE (period_month);
alter table public.deal_documents add constraint deal_documents_pkey PRIMARY KEY (id);
alter table public.deal_documents add constraint deal_documents_deal_id_party_doc_key_key UNIQUE (deal_id, party, doc_key);
alter table public.deal_status_history add constraint deal_status_history_pkey PRIMARY KEY (id);
alter table public.deals add constraint deals_pkey PRIMARY KEY (id);
alter table public.deals add constraint deals_code_key UNIQUE (code);
alter table public.deals add constraint deals_lead_id_key UNIQUE (lead_id);
alter table public.deals add constraint deals_proposal_id_key UNIQUE (proposal_id);
alter table public.features add constraint features_pkey PRIMARY KEY (id);
alter table public.features add constraint features_key_key UNIQUE (key);
alter table public.integration_events add constraint integration_events_pkey PRIMARY KEY (id);
alter table public.lead_notes add constraint lead_notes_pkey PRIMARY KEY (id);
alter table public.lead_preferences add constraint lead_preferences_pkey PRIMARY KEY (lead_id);
alter table public.lead_property_matches add constraint lead_property_matches_pkey PRIMARY KEY (id);
alter table public.lead_property_matches add constraint lead_property_matches_lead_id_property_id_key UNIQUE (lead_id, property_id);
alter table public.lead_source_history add constraint lead_source_history_pkey PRIMARY KEY (id);
alter table public.lead_status_history add constraint lead_status_history_pkey PRIMARY KEY (id);
alter table public.leads add constraint leads_pkey PRIMARY KEY (id);
alter table public.neighborhoods add constraint neighborhoods_pkey PRIMARY KEY (id);
alter table public.organization_members add constraint organization_members_pkey PRIMARY KEY (id);
alter table public.organization_members add constraint organization_members_organization_id_user_id_key UNIQUE (organization_id, user_id);
alter table public.organizations add constraint organizations_pkey PRIMARY KEY (id);
alter table public.organizations add constraint organizations_slug_key UNIQUE (slug);
alter table public.owner_captures add constraint owner_captures_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.properties add constraint properties_pkey PRIMARY KEY (id);
alter table public.properties add constraint properties_code_key UNIQUE (code);
alter table public.properties add constraint properties_slug_key UNIQUE (slug);
alter table public.property_documents add constraint property_documents_pkey PRIMARY KEY (id);
alter table public.property_documents add constraint property_documents_property_id_doc_key_key UNIQUE (property_id, doc_key);
alter table public.property_features add constraint property_features_pkey PRIMARY KEY (property_id, feature_id);
alter table public.property_images add constraint property_images_pkey PRIMARY KEY (id);
alter table public.property_management add constraint property_management_pkey PRIMARY KEY (property_id);
alter table public.property_management add constraint property_management_source_capture_id_key UNIQUE (source_capture_id);
alter table public.property_price_history add constraint property_price_history_pkey PRIMARY KEY (id);
alter table public.property_status_history add constraint property_status_history_pkey PRIMARY KEY (id);
alter table public.proposal_status_history add constraint proposal_status_history_pkey PRIMARY KEY (id);
alter table public.proposals add constraint proposals_pkey PRIMARY KEY (id);
alter table public.proposals add constraint proposals_code_key UNIQUE (code);
alter table public.rental_adjustments add constraint rental_adjustments_pkey PRIMARY KEY (id);
alter table public.rental_cases add constraint rental_cases_pkey PRIMARY KEY (id);
alter table public.rental_cases add constraint rental_cases_property_id_key UNIQUE (property_id);
alter table public.rental_charges add constraint rental_charges_pkey PRIMARY KEY (id);
alter table public.rental_charges add constraint rental_charges_contract_id_reference_month_key UNIQUE (contract_id, reference_month);
alter table public.rental_collection_actions add constraint rental_collection_actions_pkey PRIMARY KEY (id);
alter table public.rental_contract_tenants add constraint rental_contract_tenants_pkey PRIMARY KEY (id);
alter table public.rental_contract_tenants add constraint rental_contract_tenants_contract_id_tenant_id_key UNIQUE (contract_id, tenant_id);
alter table public.rental_contracts add constraint rental_contracts_pkey PRIMARY KEY (id);
alter table public.rental_contracts add constraint rental_contracts_code_key UNIQUE (code);
alter table public.rental_documents add constraint rental_documents_pkey PRIMARY KEY (id);
alter table public.rental_documents add constraint rental_documents_contract_id_doc_key_key UNIQUE (contract_id, doc_key);
alter table public.rental_guarantees add constraint rental_guarantees_pkey PRIMARY KEY (id);
alter table public.rental_guarantees add constraint rental_guarantees_contract_id_key UNIQUE (contract_id);
alter table public.rental_inspections add constraint rental_inspections_pkey PRIMARY KEY (id);
alter table public.rental_maintenance add constraint rental_maintenance_pkey PRIMARY KEY (id);
alter table public.rental_payments add constraint rental_payments_pkey PRIMARY KEY (id);
alter table public.rental_payments add constraint rental_payments_contract_id_reference_month_key UNIQUE (contract_id, reference_month);
alter table public.rental_process_tenants add constraint rental_process_tenants_pkey PRIMARY KEY (id);
alter table public.rental_process_tenants add constraint rental_process_tenants_process_id_tenant_id_key UNIQUE (process_id, tenant_id);
alter table public.rental_processes add constraint rental_processes_pkey PRIMARY KEY (id);
alter table public.rental_stage_history add constraint rental_stage_history_pkey PRIMARY KEY (id);
alter table public.rental_status_history add constraint rental_status_history_pkey PRIMARY KEY (id);
alter table public.rental_tenants add constraint rental_tenants_pkey PRIMARY KEY (id);
alter table public.rental_transfers add constraint rental_transfers_pkey PRIMARY KEY (id);
alter table public.rental_transfers add constraint rental_transfers_charge_id_key UNIQUE (charge_id);
alter table public.response_templates add constraint response_templates_pkey PRIMARY KEY (id);
alter table public.response_templates add constraint response_templates_name_key UNIQUE (name);
alter table public.site_events add constraint site_events_pkey PRIMARY KEY (id);
alter table public.site_visits add constraint site_visits_pkey PRIMARY KEY (id);
alter table public.social_messages add constraint social_messages_pkey PRIMARY KEY (id);
alter table public.team_activity_log add constraint team_activity_log_pkey PRIMARY KEY (id);;
