CREATE POLICY admin_manage_agency_settings ON public.agency_public_settings AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_agency_settings ON public.agency_public_settings AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY team_manage_agency_settings ON public.agency_public_settings AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('settings.manage'::text)) WITH CHECK (has_permission('settings.manage'::text));
CREATE POLICY admin_manage_appointments ON public.appointments AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_insert_appointments ON public.appointments AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK ((lead_id IS NOT NULL));
CREATE POLICY team_manage_appointments ON public.appointments AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('appointments.manage'::text)) WITH CHECK (has_permission('appointments.manage'::text));
CREATE POLICY team_read_appointments ON public.appointments AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('appointments.view'::text));
CREATE POLICY admin_manage_capture_documents ON public.capture_documents AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_capture_documents ON public.capture_documents AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('captures.manage'::text)) WITH CHECK (has_permission('captures.manage'::text));
CREATE POLICY admin_manage_capture_notes ON public.capture_notes AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_capture_notes ON public.capture_notes AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('captures.manage'::text)) WITH CHECK (has_permission('captures.manage'::text));
CREATE POLICY admin_read_capture_status_history ON public.capture_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_capture_status_history ON public.capture_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('captures.view'::text));
CREATE POLICY admin_manage_cities ON public.cities AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_active_cities ON public.cities AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY team_manage_cities ON public.cities AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY admin_manage_crm_documents ON public.crm_documents AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_crm_documents ON public.crm_documents AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('documents.manage'::text)) WITH CHECK (has_permission('documents.manage'::text));
CREATE POLICY team_read_crm_documents ON public.crm_documents AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('documents.view'::text));
CREATE POLICY admin_manage_crm_monthly_goals ON public.crm_monthly_goals AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_crm_monthly_goals ON public.crm_monthly_goals AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('management.manage'::text)) WITH CHECK (has_permission('management.manage'::text));
CREATE POLICY team_read_crm_monthly_goals ON public.crm_monthly_goals AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('management.view'::text));
CREATE POLICY admin_manage_deal_documents ON public.deal_documents AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_deal_documents ON public.deal_documents AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('deals.manage'::text)) WITH CHECK (has_permission('deals.manage'::text));
CREATE POLICY admin_read_deal_history ON public.deal_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_deal_history ON public.deal_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('deals.view'::text));
CREATE POLICY admin_manage_deals ON public.deals AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_deals ON public.deals AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('deals.manage'::text)) WITH CHECK (has_permission('deals.manage'::text));
CREATE POLICY team_read_deals ON public.deals AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('deals.view'::text));
CREATE POLICY admin_manage_features ON public.features AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_active_features ON public.features AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY team_manage_features ON public.features AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY admin_read_integration_events ON public.integration_events AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_integration_events ON public.integration_events AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission('health.view'::text) OR has_permission('integrations.manage'::text)));
CREATE POLICY admin_manage_lead_notes ON public.lead_notes AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_lead_notes ON public.lead_notes AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('leads.manage'::text)) WITH CHECK (has_permission('leads.manage'::text));
CREATE POLICY admin_manage_lead_preferences ON public.lead_preferences AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_lead_preferences ON public.lead_preferences AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('leads.manage'::text)) WITH CHECK (has_permission('leads.manage'::text));
CREATE POLICY admin_manage_lead_property_matches ON public.lead_property_matches AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_lead_property_matches ON public.lead_property_matches AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('leads.manage'::text)) WITH CHECK (has_permission('leads.manage'::text));
CREATE POLICY admin_read_lead_source_history ON public.lead_source_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_lead_source_history ON public.lead_source_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('leads.view'::text));
CREATE POLICY admin_read_lead_status_history ON public.lead_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_lead_status_history ON public.lead_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('leads.view'::text));
CREATE POLICY admin_manage_leads ON public.leads AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_insert_leads ON public.leads AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK ((((length(TRIM(BOTH FROM name)) >= 2) AND (length(TRIM(BOTH FROM name)) <= 120)) AND (whatsapp IS NOT NULL) AND ((length(regexp_replace(whatsapp, '\D'::text, ''::text, 'g'::text)) >= 10) AND (length(regexp_replace(whatsapp, '\D'::text, ''::text, 'g'::text)) <= 15))));
CREATE POLICY team_manage_leads ON public.leads AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('leads.manage'::text)) WITH CHECK (has_permission('leads.manage'::text));
CREATE POLICY team_read_leads ON public.leads AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('leads.view'::text));;
