CREATE OR REPLACE FUNCTION public.log_team_activity()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare new_json jsonb; old_json jsonb; changed jsonb:='[]'::jsonb; rid text; org_id uuid; begin if tg_op='INSERT' then new_json:=to_jsonb(new); rid:=new_json->>'id'; elsif tg_op='UPDATE' then new_json:=to_jsonb(new); old_json:=to_jsonb(old); rid:=new_json->>'id'; select coalesce(jsonb_agg(k.key order by k.key),'[]'::jsonb) into changed from jsonb_object_keys(new_json) as k(key) where (new_json->k.key) is distinct from (old_json->k.key) and k.key not in ('updated_at'); else old_json:=to_jsonb(old); rid:=old_json->>'id'; end if; org_id:=public.current_organization_id(); if org_id is null then select id into org_id from public.organizations where slug='matos-negocios-imobiliarios' limit 1; end if; insert into public.team_activity_log(organization_id,actor_user_id,table_name,record_id,action,changed_fields) values(org_id,auth.uid(),tg_table_name,rid,tg_op,changed); if tg_op='DELETE' then return old; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.organization_team_members()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$ select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'organization_id',m.organization_id,'user_id',m.user_id,'role',m.role,'status',m.status,'permissions',coalesce(m.permissions,'{}'::jsonb),'invited_at',m.invited_at,'joined_at',m.joined_at,'created_at',m.created_at,'updated_at',m.updated_at,'assigned_leads',(select count(*) from public.leads l where l.assigned_to=m.user_id),'assigned_properties',(select count(*) from public.properties pr where pr.assigned_to=m.user_id),'profile',jsonb_build_object('id',p.id,'full_name',p.full_name,'email',p.email,'last_seen_at',p.last_seen_at)) order by case m.role when 'owner' then 1 when 'admin' then 2 when 'broker' then 3 else 4 end,m.created_at),'[]'::jsonb) from public.organization_members m join public.profiles p on p.id=m.user_id where m.organization_id=public.current_organization_id() and public.has_permission('team.view'); $function$;

CREATE OR REPLACE FUNCTION public.protect_last_owner()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare remaining_owners integer; actor_role text; begin actor_role:=public.current_team_role(); if auth.uid() is not null and actor_role='admin' then if old.role='owner' or (tg_op<>'DELETE' and new.role='owner') then raise exception 'Somente um proprietário pode alterar outro proprietário.'; end if; end if; if old.role='owner' and old.status='active' and (tg_op='DELETE' or new.role<>'owner' or new.status<>'active') then select count(*) into remaining_owners from public.organization_members m where m.organization_id=old.organization_id and m.role='owner' and m.status='active' and m.id<>old.id; if remaining_owners=0 then raise exception 'A organização precisa manter pelo menos um proprietário ativo.'; end if; end if; if tg_op='DELETE' then return old; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.stamp_assignment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if tg_op='INSERT' then if new.assigned_to is null and auth.uid() is not null then new.assigned_to:=auth.uid(); end if; if new.assigned_to is not null then new.assigned_by:=coalesce(auth.uid(),new.assigned_by); new.assigned_at:=coalesce(new.assigned_at,now()); end if; elsif new.assigned_to is distinct from old.assigned_to then new.assigned_by:=auth.uid(); new.assigned_at:=case when new.assigned_to is null then null else now() end; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.team_assignment_summary()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$ select coalesce(jsonb_agg(jsonb_build_object('user_id',m.user_id,'full_name',p.full_name,'email',p.email,'role',m.role,'status',m.status,'leads_count',(select count(*) from public.leads l where l.assigned_to=m.user_id),'properties_count',(select count(*) from public.properties pr where pr.assigned_to=m.user_id)) order by case m.role when 'owner' then 1 when 'admin' then 2 when 'broker' then 3 else 4 end,coalesce(p.full_name,p.email)),'[]'::jsonb) from public.organization_members m join public.profiles p on p.id=m.user_id where m.organization_id=public.current_organization_id() and public.has_permission('team.view'); $function$;

CREATE OR REPLACE FUNCTION public.team_assignment_summary(p_user_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare org_id uuid; result jsonb; begin if not public.has_permission('team.view') then raise exception 'Sem permissão para visualizar a equipe.'; end if; org_id:=public.current_organization_id(); if org_id is null then raise exception 'Organização não encontrada.'; end if; if not exists(select 1 from public.organization_members m where m.organization_id=org_id and m.user_id=p_user_id) then raise exception 'O usuário informado não pertence à sua empresa.'; end if; select jsonb_build_object('leads',(select count(*) from public.leads where assigned_to=p_user_id),'properties',(select count(*) from public.properties where assigned_to=p_user_id),'appointments',(select count(*) from public.appointments where assigned_to=p_user_id),'owner_captures',(select count(*) from public.owner_captures where assigned_to=p_user_id),'proposals',(select count(*) from public.proposals where assigned_to=p_user_id),'deals',(select count(*) from public.deals where assigned_to=p_user_id)) into result; return result; end; $function$;

CREATE OR REPLACE FUNCTION public.team_portfolio_summary(p_user_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_org uuid; v_role text; v_is_member boolean; v_result jsonb; begin v_org:=public.current_organization_id(); v_role:=public.current_team_role(); if v_org is null then raise exception 'Empresa não encontrada para o usuário atual.'; end if; if v_role not in ('owner','admin') then raise exception 'Você não tem permissão para consultar carteiras da equipe.'; end if; select exists(select 1 from public.organization_members m where m.organization_id=v_org and m.user_id=p_user_id) into v_is_member; if not v_is_member then raise exception 'O usuário informado não pertence a esta empresa.'; end if; select jsonb_build_object('leads',(select count(*) from public.leads where assigned_to=p_user_id),'properties',(select count(*) from public.properties where assigned_to=p_user_id),'appointments',(select count(*) from public.appointments where assigned_to=p_user_id),'captures',(select count(*) from public.owner_captures where assigned_to=p_user_id),'proposals',(select count(*) from public.proposals where assigned_to=p_user_id),'deals',(select count(*) from public.deals where assigned_to=p_user_id)) into v_result; return v_result; end; $function$;;
