-- Company finance operational cycle
create table if not exists public.finance_recurring_entries (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null default public.current_organization_id() references public.organizations(id) on delete cascade,
 description text not null, direction text not null check(direction in ('income','expense')), amount numeric(14,2) not null check(amount>0),
 account_id uuid not null references public.finance_accounts(id), category_id uuid references public.finance_categories(id),
 frequency text not null default 'monthly' check(frequency in ('weekly','monthly','quarterly','yearly')), next_due_date date not null,
 active boolean not null default true, notes text, created_by uuid default auth.uid() references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.finance_recurring_entries enable row level security;
drop policy if exists finance_recurring_entries_select on public.finance_recurring_entries;
drop policy if exists finance_recurring_entries_manage on public.finance_recurring_entries;
create policy finance_recurring_entries_select on public.finance_recurring_entries for select to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.view'));
create policy finance_recurring_entries_manage on public.finance_recurring_entries for all to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.manage')) with check(organization_id=public.current_organization_id() and public.has_permission('financial.manage'));
create index if not exists finance_recurring_entries_org_due_idx on public.finance_recurring_entries(organization_id,next_due_date) where active=true;

create or replace function public.create_finance_account(p_name text,p_account_type text default 'bank',p_opening_balance numeric default 0) returns public.finance_accounts language plpgsql security definer set search_path=public as $$ declare v public.finance_accounts; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; if nullif(trim(p_name),'') is null then raise exception 'Nome da conta é obrigatório'; end if; if coalesce(p_opening_balance,0)<0 then raise exception 'Saldo inicial não pode ser negativo'; end if; insert into public.finance_accounts(organization_id,name,account_type,opening_balance) values(public.current_organization_id(),trim(p_name),coalesce(nullif(trim(p_account_type),''),'bank'),coalesce(p_opening_balance,0)) returning * into v; return v; end $$;
create or replace function public.update_finance_account(p_id uuid,p_name text,p_account_type text,p_active boolean) returns public.finance_accounts language plpgsql security definer set search_path=public as $$ declare v public.finance_accounts; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; update public.finance_accounts set name=trim(p_name),account_type=coalesce(nullif(trim(p_account_type),''),account_type),active=coalesce(p_active,active) where id=p_id and organization_id=public.current_organization_id() returning * into v; if not found then raise exception 'Conta financeira não encontrada'; end if; return v; end $$;
create or replace function public.create_finance_category(p_name text,p_direction text) returns public.finance_categories language plpgsql security definer set search_path=public as $$ declare v public.finance_categories; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; if nullif(trim(p_name),'') is null or p_direction not in ('income','expense','both') then raise exception 'Categoria financeira inválida'; end if; insert into public.finance_categories(organization_id,name,direction) values(public.current_organization_id(),trim(p_name),p_direction) returning * into v; return v; end $$;
create or replace function public.update_finance_category(p_id uuid,p_name text,p_direction text,p_active boolean) returns public.finance_categories language plpgsql security definer set search_path=public as $$ declare v public.finance_categories; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; if p_direction not in ('income','expense','both') then raise exception 'Direção inválida'; end if; update public.finance_categories set name=trim(p_name),direction=p_direction,active=coalesce(p_active,active) where id=p_id and organization_id=public.current_organization_id() returning * into v; if not found then raise exception 'Categoria não encontrada'; end if; return v; end $$;
create or replace function public.create_finance_entry_secure(p_description text,p_direction text,p_amount numeric,p_due_date date,p_status text,p_account_id uuid,p_category_id uuid,p_notes text default null,p_paid_at timestamptz default null,p_managed_funds boolean default false,p_property_id uuid default null,p_deal_id uuid default null,p_lead_id uuid default null,p_rental_charge_id uuid default null,p_rental_payment_id uuid default null,p_rental_transfer_id uuid default null) returns public.finance_entries language plpgsql security definer set search_path=public as $$ declare v public.finance_entries; c public.finance_categories; a public.finance_accounts; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; if p_direction not in ('income','expense') or p_amount is null or p_amount<=0 or p_status not in ('pending','paid','cancelled') then raise exception 'Lançamento financeiro inválido'; end if; select * into a from public.finance_accounts where id=p_account_id and organization_id=public.current_organization_id(); if not found then raise exception 'Conta financeira inválida'; end if; if p_category_id is not null then select * into c from public.finance_categories where id=p_category_id and organization_id=public.current_organization_id() and active; if not found or c.direction not in(p_direction,'both') then raise exception 'Categoria incompatível'; end if; end if; insert into public.finance_entries(organization_id,description,direction,amount,due_date,status,account_id,category_id,notes,paid_at,managed_funds,property_id,deal_id,lead_id,rental_charge_id,rental_payment_id,rental_transfer_id) values(public.current_organization_id(),trim(p_description),p_direction,p_amount,p_due_date,p_status,p_account_id,p_category_id,nullif(trim(p_notes),''),case when p_status='paid' then coalesce(p_paid_at,now()) end,p_managed_funds,p_property_id,p_deal_id,p_lead_id,p_rental_charge_id,p_rental_payment_id,p_rental_transfer_id) returning * into v; return v; end $$;
create or replace function public.update_finance_entry_secure(p_id uuid,p_description text,p_direction text,p_amount numeric,p_due_date date,p_status text,p_account_id uuid,p_category_id uuid,p_notes text default null,p_paid_at timestamptz default null) returns public.finance_entries language plpgsql security definer set search_path=public as $$ declare v public.finance_entries; c public.finance_categories; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; if p_direction not in('income','expense') or p_amount is null or p_amount<=0 or p_status not in('pending','paid','cancelled') then raise exception 'Lançamento inválido'; end if; if p_category_id is not null then select * into c from public.finance_categories where id=p_category_id and organization_id=public.current_organization_id() and active; if not found or c.direction not in(p_direction,'both') then raise exception 'Categoria incompatível'; end if; end if; update public.finance_entries set description=trim(p_description),direction=p_direction,amount=p_amount,due_date=p_due_date,status=p_status,account_id=p_account_id,category_id=p_category_id,notes=nullif(trim(p_notes),''),paid_at=case when p_status='paid' then coalesce(p_paid_at,now()) end where id=p_id and organization_id=public.current_organization_id() returning * into v; if not found then raise exception 'Lançamento não encontrado'; end if; return v; end $$;
create or replace function public.delete_finance_entry_secure(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; delete from public.finance_entries where id=p_id and organization_id=public.current_organization_id(); end $$;
create or replace function public.finance_dashboard_metrics(p_start_date date,p_end_date date) returns jsonb language plpgsql security definer set search_path=public as $$ declare v jsonb; begin if not public.has_permission('financial.view') then raise exception 'Permissão financial.view necessária'; end if; with base as (select * from public.finance_entries where organization_id=public.current_organization_id() and coalesce(due_date,paid_at::date) between p_start_date and p_end_date and managed_funds=false and status<>'cancelled'), monthly_data as (select to_char(date_trunc('month',coalesce(due_date,paid_at::date)),'YYYY-MM') as month_key,coalesce(sum(amount) filter(where direction='income' and status='paid'),0) income_paid,coalesce(sum(amount) filter(where direction='expense' and status='paid'),0) expense_paid,coalesce(sum(amount) filter(where direction='income' and status='pending'),0) income_pending,coalesce(sum(amount) filter(where direction='expense' and status='pending'),0) expense_pending from base group by 1 order by 1), categories_data as (select c.name,e.direction,sum(e.amount) amount from base e join public.finance_categories c on c.id=e.category_id where e.status='paid' group by c.name,e.direction order by amount desc) select jsonb_build_object('months',coalesce((select jsonb_agg(to_jsonb(monthly_data)) from monthly_data),'[]'::jsonb),'categories',coalesce((select jsonb_agg(to_jsonb(categories_data)) from categories_data),'[]'::jsonb),'overdue_receivable',coalesce((select sum(amount) from base where direction='income' and status='pending' and due_date<current_date),0),'overdue_payable',coalesce((select sum(amount) from base where direction='expense' and status='pending' and due_date<current_date),0)) into v; return v; end $$;
create or replace function public.generate_due_recurring_finance_entries(p_until_date date default current_date) returns integer language plpgsql security definer set search_path=public as $$ declare r record; n integer:=0; d date; begin if not public.has_permission('financial.manage') then raise exception 'Permissão financial.manage necessária'; end if; for r in select * from public.finance_recurring_entries where organization_id=public.current_organization_id() and active and next_due_date<=p_until_date order by next_due_date loop d:=r.next_due_date; while d<=p_until_date loop perform public.create_finance_entry_secure(r.description,r.direction,r.amount,d,'pending',r.account_id,r.category_id,r.notes,null,false); n:=n+1; d:=case r.frequency when 'weekly' then d+7 when 'monthly' then(d+interval '1 month')::date when 'quarterly' then(d+interval '3 months')::date when 'yearly' then(d+interval '1 year')::date end; end loop; update public.finance_recurring_entries set next_due_date=d,updated_at=now() where id=r.id; end loop; return n; end $$;
revoke all on function public.create_finance_account(text,text,numeric) from public,anon; grant execute on function public.create_finance_account(text,text,numeric) to authenticated;
revoke all on function public.update_finance_account(uuid,text,text,boolean) from public,anon; grant execute on function public.update_finance_account(uuid,text,text,boolean) to authenticated;
revoke all on function public.create_finance_category(text,text) from public,anon; grant execute on function public.create_finance_category(text,text) to authenticated;
revoke all on function public.update_finance_category(uuid,text,text,boolean) from public,anon; grant execute on function public.update_finance_category(uuid,text,text,boolean) to authenticated;
revoke all on function public.create_finance_entry_secure(text,text,numeric,date,text,uuid,uuid,text,timestamptz,boolean,uuid,uuid,uuid,uuid,uuid,uuid) from public,anon; grant execute on function public.create_finance_entry_secure(text,text,numeric,date,text,uuid,uuid,text,timestamptz,boolean,uuid,uuid,uuid,uuid,uuid,uuid) to authenticated;
revoke all on function public.update_finance_entry_secure(uuid,text,text,numeric,date,text,uuid,uuid,text,timestamptz) from public,anon; grant execute on function public.update_finance_entry_secure(uuid,text,text,numeric,date,text,uuid,uuid,text,timestamptz) to authenticated;
revoke all on function public.delete_finance_entry_secure(uuid) from public,anon; grant execute on function public.delete_finance_entry_secure(uuid) to authenticated;
revoke all on function public.finance_dashboard_metrics(date,date) from public,anon; grant execute on function public.finance_dashboard_metrics(date,date) to authenticated;
revoke all on function public.generate_due_recurring_finance_entries(date) from public,anon; grant execute on function public.generate_due_recurring_finance_entries(date) to authenticated;
drop policy if exists finance_accounts_select on public.finance_accounts; drop policy if exists finance_accounts_manage on public.finance_accounts;
create policy finance_accounts_select on public.finance_accounts for select to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.view'));
create policy finance_accounts_manage on public.finance_accounts for all to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.manage')) with check(organization_id=public.current_organization_id());
drop policy if exists finance_categories_select on public.finance_categories; drop policy if exists finance_categories_manage on public.finance_categories;
create policy finance_categories_select on public.finance_categories for select to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.view'));
create policy finance_categories_manage on public.finance_categories for all to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.manage'));
drop policy if exists finance_entries_select on public.finance_entries; drop policy if exists finance_entries_manage on public.finance_entries;
create policy finance_entries_select on public.finance_entries for select to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.view'));
create policy finance_entries_manage on public.finance_entries for all to authenticated using(organization_id=public.current_organization_id() and public.has_permission('financial.manage'));
