CREATE INDEX appointments_created_at_idx ON public.appointments USING btree (created_at DESC);
CREATE INDEX appointments_lead_idx ON public.appointments USING btree (lead_id);
CREATE INDEX appointments_property_idx ON public.appointments USING btree (property_id);
CREATE INDEX appointments_status_idx ON public.appointments USING btree (status);
CREATE INDEX capture_documents_capture_idx ON public.capture_documents USING btree (capture_id);
CREATE INDEX capture_notes_capture_idx ON public.capture_notes USING btree (capture_id, created_at DESC);
CREATE INDEX capture_status_history_capture_idx ON public.capture_status_history USING btree (capture_id, created_at DESC);
CREATE UNIQUE INDEX cities_name_state_unique ON public.cities USING btree (lower(name), lower((COALESCE(state_code, ''::character varying))::text));
CREATE INDEX crm_documents_capture_idx ON public.crm_documents USING btree (capture_id) WHERE (capture_id IS NOT NULL);
CREATE INDEX crm_documents_created_idx ON public.crm_documents USING btree (created_at DESC);
CREATE INDEX crm_documents_deal_idx ON public.crm_documents USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE INDEX crm_documents_expiry_idx ON public.crm_documents USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX crm_documents_lead_idx ON public.crm_documents USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX crm_documents_property_idx ON public.crm_documents USING btree (property_id) WHERE (property_id IS NOT NULL);
CREATE INDEX crm_documents_proposal_idx ON public.crm_documents USING btree (proposal_id) WHERE (proposal_id IS NOT NULL);
CREATE INDEX crm_documents_rental_contract_idx ON public.crm_documents USING btree (rental_contract_id) WHERE (rental_contract_id IS NOT NULL);
CREATE INDEX crm_documents_rental_idx ON public.crm_documents USING btree (rental_contract_id) WHERE (rental_contract_id IS NOT NULL);
CREATE INDEX crm_documents_rental_tenant_idx ON public.crm_documents USING btree (rental_tenant_id) WHERE (rental_tenant_id IS NOT NULL);
CREATE INDEX crm_documents_status_idx ON public.crm_documents USING btree (status, created_at DESC);
CREATE INDEX crm_monthly_goals_period_idx ON public.crm_monthly_goals USING btree (period_month DESC);
CREATE INDEX deal_documents_deal_idx ON public.deal_documents USING btree (deal_id, party, display_order);
CREATE INDEX deal_status_history_deal_idx ON public.deal_status_history USING btree (deal_id, created_at DESC);
CREATE INDEX deals_commission_due_idx ON public.deals USING btree (commission_due_date);
CREATE INDEX deals_commission_status_idx ON public.deals USING btree (commission_status);
CREATE INDEX deals_created_at_idx ON public.deals USING btree (created_at DESC);
CREATE INDEX deals_property_idx ON public.deals USING btree (property_id);
CREATE INDEX deals_status_idx ON public.deals USING btree (status);
CREATE INDEX integration_events_created_at_idx ON public.integration_events USING btree (created_at DESC);
CREATE INDEX lead_notes_lead_created_idx ON public.lead_notes USING btree (lead_id, created_at DESC);
CREATE INDEX lead_preferences_updated_idx ON public.lead_preferences USING btree (updated_at DESC);
CREATE INDEX lead_property_matches_lead_idx ON public.lead_property_matches USING btree (lead_id, status, updated_at DESC);
CREATE INDEX lead_property_matches_property_idx ON public.lead_property_matches USING btree (property_id, status, updated_at DESC);
CREATE INDEX lead_source_history_lead_idx ON public.lead_source_history USING btree (lead_id, occurred_at DESC);
CREATE INDEX lead_status_history_lead_created_idx ON public.lead_status_history USING btree (lead_id, created_at DESC);
CREATE INDEX leads_closed_at_idx ON public.leads USING btree (closed_at);
CREATE INDEX leads_created_at_idx ON public.leads USING btree (created_at DESC);
CREATE UNIQUE INDEX leads_external_lead_unique ON public.leads USING btree (source_platform, external_lead_id) WHERE (external_lead_id IS NOT NULL);
CREATE INDEX leads_initial_source_platform_idx ON public.leads USING btree (initial_source_platform);
CREATE UNIQUE INDEX leads_instagram_contact_unique ON public.leads USING btree (source_platform, external_contact_id) WHERE ((source_platform = 'instagram'::text) AND (source_channel = 'direct'::text) AND (external_contact_id IS NOT NULL));
CREATE INDEX leads_last_inbound_at_idx ON public.leads USING btree (last_inbound_at DESC);
CREATE INDEX leads_last_message_at_idx ON public.leads USING btree (last_message_at DESC);
CREATE INDEX leads_last_source_platform_idx ON public.leads USING btree (last_source_platform);
CREATE INDEX leads_next_action_at_idx ON public.leads USING btree (next_action_at);
CREATE INDEX leads_property_idx ON public.leads USING btree (property_id);
CREATE INDEX leads_source_channel_idx ON public.leads USING btree (source_channel);
CREATE INDEX leads_source_platform_idx ON public.leads USING btree (source_platform);
CREATE INDEX leads_status_idx ON public.leads USING btree (status);
CREATE INDEX leads_whatsapp_phone_number_id_idx ON public.leads USING btree (whatsapp_phone_number_id) WHERE (whatsapp_phone_number_id IS NOT NULL);
CREATE UNIQUE INDEX leads_whatsapp_wa_id_unique ON public.leads USING btree (whatsapp_wa_id) WHERE (whatsapp_wa_id IS NOT NULL);;
