alter table public.agency_public_settings add constraint agency_public_settings_id_check CHECK (id = 1);
alter table public.appointments add constraint appointments_status_check CHECK (status = ANY (ARRAY['requested'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text]));
alter table public.capture_documents add constraint capture_documents_status_check CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'not_applicable'::text]));
alter table public.crm_documents add constraint crm_documents_category_check CHECK (category = ANY (ARRAY['property'::text, 'owner'::text, 'buyer'::text, 'seller'::text, 'proposal'::text, 'authorization'::text, 'contract'::text, 'deed_registry'::text, 'finance'::text, 'personal'::text, 'proof'::text, 'tenant'::text, 'rental'::text, 'inspection'::text, 'other'::text]));
alter table public.crm_documents add constraint crm_documents_file_size_nonnegative CHECK (file_size IS NULL OR file_size >= 0);
alter table public.crm_documents add constraint crm_documents_single_context CHECK (num_nonnulls(property_id, lead_id, capture_id, proposal_id, deal_id, rental_tenant_id, rental_contract_id) <= 1);
alter table public.crm_documents add constraint crm_documents_status_check CHECK (status = ANY (ARRAY['pending_review'::text, 'approved'::text, 'rejected'::text]));
alter table public.crm_documents add constraint crm_documents_validity_order CHECK (expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_captures_goal_check CHECK (captures_goal >= 0);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_commission_goal_check CHECK (commission_goal >= 0::numeric);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_deals_goal_check CHECK (deals_goal >= 0);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_first_day CHECK (period_month = date_trunc('month'::text, period_month::timestamp with time zone)::date);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_leads_goal_check CHECK (leads_goal >= 0);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_proposals_goal_check CHECK (proposals_goal >= 0);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_sales_value_goal_check CHECK (sales_value_goal >= 0::numeric);
alter table public.crm_monthly_goals add constraint crm_monthly_goals_visits_goal_check CHECK (visits_goal >= 0);
alter table public.deal_documents add constraint deal_documents_party_check CHECK (party = ANY (ARRAY['buyer'::text, 'seller'::text, 'transaction'::text]));
alter table public.deal_documents add constraint deal_documents_status_check CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'validated'::text, 'not_applicable'::text]));
alter table public.deals add constraint deals_commission_payer_check CHECK (commission_payer IS NULL OR (commission_payer = ANY (ARRAY['seller'::text, 'buyer'::text, 'both'::text, 'other'::text])));
alter table public.deals add constraint deals_commission_percent_range CHECK (commission_percent IS NULL OR commission_percent >= 0::numeric AND commission_percent <= 100::numeric);
alter table public.deals add constraint deals_commission_received_nonnegative CHECK (commission_received_amount >= 0::numeric);
alter table public.deals add constraint deals_commission_status_check CHECK (commission_status = ANY (ARRAY['pending'::text, 'partial'::text, 'received'::text]));
alter table public.deals add constraint deals_commission_value_nonnegative CHECK (commission_value IS NULL OR commission_value >= 0::numeric);
alter table public.deals add constraint deals_contract_status_check CHECK (contract_status = ANY (ARRAY['pending'::text, 'sent'::text, 'signed'::text]));
alter table public.deals add constraint deals_deed_status_check CHECK (deed_status = ANY (ARRAY['not_applicable'::text, 'pending'::text, 'scheduled'::text, 'signed'::text]));
alter table public.deals add constraint deals_financing_status_check CHECK (financing_status = ANY (ARRAY['not_applicable'::text, 'pending'::text, 'analysis'::text, 'approved'::text, 'rejected'::text, 'contracted'::text]));
alter table public.deals add constraint deals_registry_status_check CHECK (registry_status = ANY (ARRAY['not_applicable'::text, 'pending'::text, 'submitted'::text, 'completed'::text]));
alter table public.deals add constraint deals_sale_value_nonnegative CHECK (sale_value IS NULL OR sale_value >= 0::numeric);
alter table public.deals add constraint deals_status_check CHECK (status = ANY (ARRAY['documents'::text, 'contract'::text, 'financing'::text, 'deed_registry'::text, 'completed'::text, 'cancelled'::text]));
alter table public.lead_preferences add constraint lead_preferences_areas_nonnegative CHECK ((min_total_area IS NULL OR min_total_area >= 0::numeric) AND (min_built_area IS NULL OR min_built_area >= 0::numeric));
alter table public.lead_preferences add constraint lead_preferences_counts_nonnegative CHECK ((min_bedrooms IS NULL OR min_bedrooms >= 0) AND (min_bathrooms IS NULL OR min_bathrooms >= 0) AND (min_parking_spaces IS NULL OR min_parking_spaces >= 0));
alter table public.lead_preferences add constraint lead_preferences_price_order CHECK (min_price IS NULL OR max_price IS NULL OR min_price <= max_price);
alter table public.lead_preferences add constraint lead_preferences_prices_nonnegative CHECK ((min_price IS NULL OR min_price >= 0::numeric) AND (max_price IS NULL OR max_price >= 0::numeric));
alter table public.lead_preferences add constraint lead_preferences_purpose_check CHECK (purpose = ANY (ARRAY['sale'::text, 'rent'::text, 'either'::text]));
alter table public.lead_preferences add constraint lead_preferences_urgency_check CHECK (urgency = ANY (ARRAY['now'::text, '30_days'::text, '90_days'::text, 'research'::text]));
alter table public.lead_property_matches add constraint lead_property_matches_score_check CHECK (score IS NULL OR score >= 0 AND score <= 100);
alter table public.lead_property_matches add constraint lead_property_matches_status_check CHECK (status = ANY (ARRAY['suggested'::text, 'interested'::text, 'visit'::text, 'discarded'::text]));
alter table public.lead_source_history add constraint lead_source_history_touch_type_check CHECK (touch_type = ANY (ARRAY['initial'::text, 'touch'::text]));
alter table public.leads add constraint leads_commission_value_nonnegative CHECK (commission_value IS NULL OR commission_value >= 0::numeric);
alter table public.leads add constraint leads_deal_value_nonnegative CHECK (deal_value IS NULL OR deal_value >= 0::numeric);
alter table public.leads add constraint leads_social_unread_count_nonnegative CHECK (social_unread_count >= 0);
alter table public.leads add constraint leads_status_check CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'visit_scheduled'::text, 'proposal'::text, 'won'::text, 'lost'::text]));
alter table public.organization_members add constraint organization_members_role_check CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'broker'::text, 'assistant'::text]));
alter table public.organization_members add constraint organization_members_status_check CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'disabled'::text]));
alter table public.organizations add constraint organizations_status_check CHECK (status = ANY (ARRAY['trial'::text, 'active'::text, 'suspended'::text, 'cancelled'::text]));
alter table public.owner_captures add constraint owner_captures_purpose_check CHECK (purpose = ANY (ARRAY['sale'::text, 'rent'::text, 'sale_and_rent'::text]));
alter table public.owner_captures add constraint owner_captures_request_type_check CHECK (request_type = ANY (ARRAY['listing'::text, 'valuation'::text]));
alter table public.owner_captures add constraint owner_captures_status_check CHECK (status = ANY (ARRAY['new'::text, 'evaluation'::text, 'documents'::text, 'authorized'::text, 'published'::text, 'lost'::text]));
alter table public.profiles add constraint profiles_role_check CHECK (role = ANY (ARRAY['user'::text, 'admin'::text]));
alter table public.properties add constraint properties_bathrooms_check CHECK (bathrooms IS NULL OR bathrooms >= 0);
alter table public.properties add constraint properties_bedrooms_check CHECK (bedrooms IS NULL OR bedrooms >= 0);
alter table public.properties add constraint properties_built_area_check CHECK (built_area IS NULL OR built_area >= 0::numeric);
alter table public.properties add constraint properties_condominium_fee_check CHECK (condominium_fee IS NULL OR condominium_fee >= 0::numeric);
alter table public.properties add constraint properties_iptu_value_check CHECK (iptu_value IS NULL OR iptu_value >= 0::numeric);
alter table public.properties add constraint properties_parking_spaces_check CHECK (parking_spaces IS NULL OR parking_spaces >= 0);
alter table public.properties add constraint properties_purpose_check CHECK (purpose = ANY (ARRAY['sale'::text, 'rent'::text, 'sale_and_rent'::text]));
alter table public.properties add constraint properties_rent_price_check CHECK (rent_price IS NULL OR rent_price >= 0::numeric);
alter table public.properties add constraint properties_sale_price_check CHECK (sale_price IS NULL OR sale_price >= 0::numeric);
alter table public.properties add constraint properties_status_check CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'reserved'::text, 'sold'::text, 'rented'::text, 'inactive'::text]));
alter table public.properties add constraint properties_suites_check CHECK (suites IS NULL OR suites >= 0);
alter table public.properties add constraint properties_total_area_check CHECK (total_area IS NULL OR total_area >= 0::numeric);
alter table public.property_documents add constraint property_documents_status_check CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'validated'::text, 'not_applicable'::text]));
alter table public.property_images add constraint property_images_display_order_check CHECK (display_order >= 0);
alter table public.property_management add constraint property_management_authorization_status_check CHECK (authorization_status = ANY (ARRAY['pending'::text, 'authorized'::text, 'expired'::text, 'not_required'::text]));
alter table public.property_management add constraint property_management_commission_payer_check CHECK (commission_payer = ANY (ARRAY['seller'::text, 'buyer'::text, 'both'::text, 'other'::text]));
alter table public.property_management add constraint property_management_commission_range CHECK (commission_percent IS NULL OR commission_percent >= 0::numeric AND commission_percent <= 100::numeric);
alter table public.property_management add constraint property_management_documentation_status_check CHECK (documentation_status = ANY (ARRAY['pending'::text, 'partial'::text, 'complete'::text]));
alter table public.property_price_history add constraint property_price_history_price_type_check CHECK (price_type = ANY (ARRAY['sale'::text, 'rent'::text]));
alter table public.proposals add constraint proposals_status_check CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'negotiation'::text, 'accepted'::text, 'rejected'::text, 'expired'::text]));
alter table public.proposals add constraint proposals_value_nonnegative CHECK (proposal_value IS NULL OR proposal_value >= 0::numeric);
alter table public.rental_cases add constraint rental_cases_stage_check CHECK (stage = ANY (ARRAY['available'::text, 'interested'::text, 'visit'::text, 'proposal'::text, 'screening'::text, 'contract'::text, 'occupied'::text, 'renewal'::text, 'vacated'::text]));
alter table public.rental_charges add constraint rental_charges_status_check CHECK (status = ANY (ARRAY['due'::text, 'paid'::text, 'overdue'::text, 'partial'::text, 'cancelled'::text]));
alter table public.rental_collection_actions add constraint rental_collection_actions_channel_check CHECK (channel = ANY (ARRAY['whatsapp'::text, 'phone'::text, 'email'::text, 'in_person'::text, 'other'::text]));
alter table public.rental_contract_tenants add constraint rental_contract_tenants_role_check CHECK (role = ANY (ARRAY['primary'::text, 'co_tenant'::text, 'responsible'::text, 'resident'::text]));
alter table public.rental_contracts add constraint rental_contract_dates_order CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date);
alter table public.rental_contracts add constraint rental_contract_positive_values CHECK (COALESCE(monthly_rent, 0::numeric) >= 0::numeric AND COALESCE(placement_fee_value, 0::numeric) >= 0::numeric AND COALESCE(condominium_amount, 0::numeric) >= 0::numeric AND COALESCE(property_tax_amount, 0::numeric) >= 0::numeric AND COALESCE(guarantee_value, 0::numeric) >= 0::numeric);
alter table public.rental_contracts add constraint rental_contracts_adjustment_index_check CHECK (adjustment_index = ANY (ARRAY['ipca'::text, 'igpm'::text, 'fixed'::text, 'none'::text, 'other'::text]));
alter table public.rental_contracts add constraint rental_contracts_administration_fee_percent_check CHECK (administration_fee_percent IS NULL OR administration_fee_percent >= 0::numeric AND administration_fee_percent <= 100::numeric);
alter table public.rental_contracts add constraint rental_contracts_due_day_check CHECK (due_day >= 1 AND due_day <= 28);
alter table public.rental_contracts add constraint rental_contracts_guarantee_type_check CHECK (guarantee_type = ANY (ARRAY['none'::text, 'deposit'::text, 'guarantor'::text, 'insurance'::text, 'capitalization'::text, 'other'::text]));
alter table public.rental_contracts add constraint rental_contracts_property_tax_payer_check CHECK (property_tax_payer = ANY (ARRAY['tenant'::text, 'owner'::text, 'included'::text]));
alter table public.rental_contracts add constraint rental_contracts_status_check CHECK (status = ANY (ARRAY['analysis'::text, 'documents'::text, 'awaiting_signature'::text, 'active'::text, 'ending'::text, 'ended'::text, 'cancelled'::text]));
alter table public.rental_documents add constraint rental_documents_party_check CHECK (party = ANY (ARRAY['tenant'::text, 'guarantee'::text, 'owner'::text, 'contract'::text, 'inspection'::text]));
alter table public.rental_documents add constraint rental_documents_status_check CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'validated'::text, 'not_applicable'::text]));
alter table public.rental_guarantees add constraint rental_guarantees_deposit_refund_status_check CHECK (deposit_refund_status = ANY (ARRAY['not_applicable'::text, 'held'::text, 'partial'::text, 'refunded'::text, 'retained'::text]));
alter table public.rental_guarantees add constraint rental_guarantees_guarantee_type_check CHECK (guarantee_type = ANY (ARRAY['guarantor'::text, 'deposit'::text, 'insurance'::text, 'capitalization'::text, 'none'::text, 'other'::text]));
alter table public.rental_inspections add constraint rental_inspections_inspection_type_check CHECK (inspection_type = ANY (ARRAY['entry'::text, 'periodic'::text, 'exit'::text]));
alter table public.rental_inspections add constraint rental_inspections_status_check CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text]));
alter table public.rental_maintenance add constraint rental_maintenance_costs_nonnegative CHECK (COALESCE(estimated_cost, 0::numeric) >= 0::numeric AND COALESCE(actual_cost, 0::numeric) >= 0::numeric);
alter table public.rental_maintenance add constraint rental_maintenance_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text]));
alter table public.rental_maintenance add constraint rental_maintenance_responsibility_check CHECK (responsibility = ANY (ARRAY['pending'::text, 'owner'::text, 'tenant'::text, 'agency'::text, 'condominium'::text]));
alter table public.rental_maintenance add constraint rental_maintenance_status_check CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'waiting'::text, 'completed'::text, 'cancelled'::text]));
alter table public.rental_payments add constraint rental_payment_values_nonnegative CHECK (rent_amount >= 0::numeric AND condominium_amount >= 0::numeric AND property_tax_amount >= 0::numeric AND other_charges >= 0::numeric AND discount_amount >= 0::numeric AND paid_amount >= 0::numeric);
alter table public.rental_payments add constraint rental_payments_status_check CHECK (status = ANY (ARRAY['pending'::text, 'overdue'::text, 'partial'::text, 'paid'::text, 'waived'::text]));
alter table public.rental_process_tenants add constraint rental_process_tenants_responsibility_check CHECK (responsibility = ANY (ARRAY['primary'::text, 'co_responsible'::text, 'resident'::text]));
alter table public.rental_processes add constraint rental_processes_analysis_status_check CHECK (analysis_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]));
alter table public.rental_processes add constraint rental_processes_stage_check CHECK (stage = ANY (ARRAY['available'::text, 'interested'::text, 'visit'::text, 'proposal'::text, 'screening'::text, 'contract'::text, 'occupied'::text, 'renewal'::text, 'vacated'::text, 'lost'::text]));
alter table public.rental_transfers add constraint rental_transfers_status_check CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'held'::text, 'cancelled'::text]));
alter table public.response_templates add constraint response_templates_channel_check CHECK (channel = ANY (ARRAY['all'::text, 'instagram'::text, 'whatsapp'::text, 'facebook'::text]));
alter table public.social_messages add constraint social_messages_delivery_status_check CHECK (delivery_status = ANY (ARRAY['received'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text]));
alter table public.social_messages add constraint social_messages_direction_check CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text]));
alter table public.team_activity_log add constraint team_activity_log_action_check CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text]));;
