-- Global in-app notifications for GOI
create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  kind text not null check (kind in ('instagram','whatsapp','form')),
  title text not null,
  body text,
  route text,
  entity_type text,
  entity_id text,
  created_at timestamptz not null default now()
);

create index if not exists app_notifications_org_created_idx
  on public.app_notifications (organization_id, created_at desc);

create table if not exists public.app_notification_reads (
  notification_id bigint not null references public.app_notifications(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

create index if not exists app_notification_reads_user_idx
  on public.app_notification_reads (user_id, notification_id);

create table if not exists public.user_notification_preferences (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  instagram_enabled boolean not null default true,
  whatsapp_enabled boolean not null default true,
  forms_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

alter table public.app_notifications enable row level security;
alter table public.app_notification_reads enable row level security;
alter table public.user_notification_preferences enable row level security;

drop policy if exists "app_notifications_select_org_members" on public.app_notifications;
create policy "app_notifications_select_org_members"
on public.app_notifications
for select
to authenticated
using (
  exists (
    select 1 from public.organization_members om
    where om.organization_id = app_notifications.organization_id
      and om.user_id = auth.uid()
      and om.status = 'active'
  )
);

drop policy if exists "app_notification_reads_select_own" on public.app_notification_reads;
create policy "app_notification_reads_select_own"
on public.app_notification_reads
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "app_notification_reads_insert_own" on public.app_notification_reads;
create policy "app_notification_reads_insert_own"
on public.app_notification_reads
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.app_notifications n
    join public.organization_members om on om.organization_id = n.organization_id
    where n.id = app_notification_reads.notification_id
      and om.user_id = auth.uid()
      and om.status = 'active'
  )
);

drop policy if exists "notification_preferences_select_own" on public.user_notification_preferences;
create policy "notification_preferences_select_own"
on public.user_notification_preferences
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "notification_preferences_insert_own" on public.user_notification_preferences;
create policy "notification_preferences_insert_own"
on public.user_notification_preferences
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.organization_members om
    where om.organization_id = user_notification_preferences.organization_id
      and om.user_id = auth.uid()
      and om.status = 'active'
  )
);

drop policy if exists "notification_preferences_update_own" on public.user_notification_preferences;
create policy "notification_preferences_update_own"
on public.user_notification_preferences
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.create_social_app_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_title text;
  v_route text;
begin
  if new.direction <> 'inbound' or new.platform not in ('instagram','whatsapp') then
    return new;
  end if;

  select name into v_name from public.leads where id = new.lead_id;

  if new.platform = 'instagram' then
    v_title := 'Nova mensagem no Instagram';
    v_route := '/admin/mensagens';
  else
    v_title := 'Nova mensagem no WhatsApp';
    v_route := '/admin/whatsapp';
  end if;

  insert into public.app_notifications (
    organization_id, kind, title, body, route, entity_type, entity_id
  ) values (
    new.organization_id,
    new.platform,
    v_title,
    concat_ws(': ', coalesce(v_name,'Novo contato'), nullif(left(coalesce(new.message_text,''),140),'')),
    v_route,
    'lead',
    new.lead_id::text
  );

  return new;
end;
$$;

drop trigger if exists trg_social_message_app_notification on public.social_messages;
create trigger trg_social_message_app_notification
after insert on public.social_messages
for each row execute function public.create_social_app_notification();

create or replace function public.create_lead_form_app_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.source = 'manual'
     or coalesce(new.source_platform,'') in ('instagram','whatsapp') then
    return new;
  end if;

  insert into public.app_notifications (
    organization_id, kind, title, body, route, entity_type, entity_id
  ) values (
    new.organization_id,
    'form',
    'Novo formulário recebido',
    concat_ws(' — ', new.name, nullif(left(coalesce(new.message,''),140),'')),
    '/admin/leads/' || new.id::text,
    'lead',
    new.id::text
  );

  return new;
end;
$$;

drop trigger if exists trg_lead_form_app_notification on public.leads;
create trigger trg_lead_form_app_notification
after insert on public.leads
for each row execute function public.create_lead_form_app_notification();

create or replace function public.create_capture_form_app_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text;
begin
  v_type := case when new.request_type = 'valuation' then 'avaliação' else 'captação' end;

  insert into public.app_notifications (
    organization_id, kind, title, body, route, entity_type, entity_id
  ) values (
    new.organization_id,
    'form',
    'Novo formulário de ' || v_type,
    concat_ws(' — ', new.owner_name, new.city_name),
    '/admin/captacoes/' || new.id::text,
    'owner_capture',
    new.id::text
  );

  return new;
end;
$$;

drop trigger if exists trg_capture_form_app_notification on public.owner_captures;
create trigger trg_capture_form_app_notification
after insert on public.owner_captures
for each row execute function public.create_capture_form_app_notification();

do $$
begin
  begin
    alter publication supabase_realtime add table public.app_notifications;
  exception
    when duplicate_object then null;
  end;
end
$$;
