CREATE POLICY admin_manage_neighborhoods ON public.neighborhoods AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_active_neighborhoods ON public.neighborhoods AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY team_manage_neighborhoods ON public.neighborhoods AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY team_manage_members ON public.organization_members AS PERMISSIVE FOR ALL TO authenticated USING (((organization_id = current_organization_id()) AND has_permission('team.manage'::text))) WITH CHECK (((organization_id = current_organization_id()) AND has_permission('team.manage'::text)));
CREATE POLICY team_read_members ON public.organization_members AS PERMISSIVE FOR SELECT TO authenticated USING ((organization_id = current_organization_id()));
CREATE POLICY members_read_own_organization ON public.organizations AS PERMISSIVE FOR SELECT TO authenticated USING ((id = current_organization_id()));
CREATE POLICY owners_manage_organization ON public.organizations AS PERMISSIVE FOR UPDATE TO authenticated USING (((id = current_organization_id()) AND (current_team_role() = 'owner'::text))) WITH CHECK (((id = current_organization_id()) AND (current_team_role() = 'owner'::text)));
CREATE POLICY admin_manage_owner_captures ON public.owner_captures AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_insert_owner_captures ON public.owner_captures AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK ((((length(TRIM(BOTH FROM owner_name)) >= 2) AND (length(TRIM(BOTH FROM owner_name)) <= 120)) AND ((length(regexp_replace(whatsapp, '\D'::text, ''::text, 'g'::text)) >= 10) AND (length(regexp_replace(whatsapp, '\D'::text, ''::text, 'g'::text)) <= 15)) AND ((length(TRIM(BOTH FROM city_name)) >= 2) AND (length(TRIM(BOTH FROM city_name)) <= 120)) AND ((length(TRIM(BOTH FROM property_type)) >= 2) AND (length(TRIM(BOTH FROM property_type)) <= 80))));
CREATE POLICY team_manage_owner_captures ON public.owner_captures AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('captures.manage'::text)) WITH CHECK (has_permission('captures.manage'::text));
CREATE POLICY team_read_owner_captures ON public.owner_captures AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('captures.view'::text));
CREATE POLICY admins_read_profiles ON public.profiles AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_profiles ON public.profiles AS PERMISSIVE FOR SELECT TO authenticated USING (((id = auth.uid()) OR is_admin() OR (EXISTS ( SELECT 1 FROM (organization_members mine JOIN organization_members other ON ((other.organization_id = mine.organization_id))) WHERE ((mine.user_id = auth.uid()) AND (mine.status = 'active'::text) AND (other.user_id = profiles.id))))));
CREATE POLICY users_read_own_profile ON public.profiles AS PERMISSIVE FOR SELECT TO authenticated USING ((id = auth.uid()));
CREATE POLICY admin_manage_properties ON public.properties AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_published_properties ON public.properties AS PERMISSIVE FOR SELECT TO anon, authenticated USING (((status = 'published'::text) AND (deleted_at IS NULL)));
CREATE POLICY team_manage_properties ON public.properties AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY team_read_properties ON public.properties AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('properties.view'::text));
CREATE POLICY admin_manage_property_documents ON public.property_documents AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_property_documents ON public.property_documents AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY admin_manage_property_features ON public.property_features AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_published_property_features ON public.property_features AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((EXISTS (SELECT 1 FROM properties p WHERE ((p.id = property_features.property_id) AND (p.status = 'published'::text) AND (p.deleted_at IS NULL)))));
CREATE POLICY team_manage_property_features ON public.property_features AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY admin_manage_property_images ON public.property_images AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY public_read_published_property_images ON public.property_images AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((EXISTS (SELECT 1 FROM properties p WHERE ((p.id = property_images.property_id) AND (p.status = 'published'::text) AND (p.deleted_at IS NULL)))));
CREATE POLICY team_manage_property_images ON public.property_images AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY admin_manage_property_management ON public.property_management AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_property_management ON public.property_management AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('properties.manage'::text)) WITH CHECK (has_permission('properties.manage'::text));
CREATE POLICY team_read_property_management ON public.property_management AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('properties.view'::text));
CREATE POLICY admin_read_property_price_history ON public.property_price_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_property_price_history ON public.property_price_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('properties.view'::text));
CREATE POLICY admin_read_property_status_history ON public.property_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_property_status_history ON public.property_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('properties.view'::text));
CREATE POLICY admin_read_proposal_history ON public.proposal_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY team_read_proposal_history ON public.proposal_status_history AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('proposals.view'::text));
CREATE POLICY admin_manage_proposals ON public.proposals AS PERMISSIVE FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY team_manage_proposals ON public.proposals AS PERMISSIVE FOR ALL TO authenticated USING (has_permission('proposals.manage'::text)) WITH CHECK (has_permission('proposals.manage'::text));
CREATE POLICY team_read_proposals ON public.proposals AS PERMISSIVE FOR SELECT TO authenticated USING (has_permission('proposals.view'::text));;
