CREATE OR REPLACE FUNCTION public.apply_proposal_business_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ declare status_changed boolean; begin if tg_op='INSERT' then status_changed:=true; else status_changed:=old.status is distinct from new.status; end if; if new.status='sent' and status_changed then new.sent_at:=coalesce(new.sent_at,now()); end if; if new.status='accepted' and status_changed then new.accepted_at:=coalesce(new.accepted_at,now()); new.rejected_at:=null; new.rejection_reason:=null; new.next_follow_up_at:=null; new.next_follow_up_text:=null; elsif new.status='rejected' and status_changed then new.rejected_at:=coalesce(new.rejected_at,now()); new.accepted_at:=null; new.next_follow_up_at:=null; new.next_follow_up_text:=null; elsif new.status='expired' and status_changed then new.next_follow_up_at:=null; new.next_follow_up_text:=null; end if; if new.status<>'rejected' then new.rejection_reason:=null; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.log_proposal_status_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if tg_op='INSERT' then insert into public.proposal_status_history(proposal_id,from_status,to_status,changed_by) values(new.id,null,new.status,auth.uid()); elsif old.status is distinct from new.status then insert into public.proposal_status_history(proposal_id,from_status,to_status,changed_by) values(new.id,old.status,new.status,auth.uid()); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.sync_lead_from_proposal()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if new.status in ('sent','negotiation','accepted') then update public.leads set status='proposal' where id=new.lead_id and status not in ('won','lost'); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.admin_refresh_expired_proposals()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare affected integer; begin if not public.has_permission('proposals.view') then raise exception 'not authorized'; end if; update public.proposals set status='expired' where status in ('sent','negotiation') and valid_until is not null and valid_until<current_date; get diagnostics affected=row_count; return affected; end; $function$;

CREATE OR REPLACE FUNCTION public.admin_proposal_metrics(days_back integer DEFAULT 90)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare start_at timestamptz; total_count bigint; open_count bigint; sent_count bigint; negotiation_count bigint; accepted_count bigint; rejected_count bigint; expired_count bigint; decided_count bigint; leads_with_proposal bigint; sales_from_proposals bigint; open_value numeric; accepted_value numeric; acceptance_rate numeric; proposal_to_sale_rate numeric; begin if not public.has_permission('proposals.view') then raise exception 'not authorized'; end if; start_at:=now()-make_interval(days=>greatest(days_back,1)); select count(*) into total_count from public.proposals where created_at>=start_at; select count(*) into open_count from public.proposals where created_at>=start_at and status in ('draft','sent','negotiation'); select count(*) into sent_count from public.proposals where created_at>=start_at and status='sent'; select count(*) into negotiation_count from public.proposals where created_at>=start_at and status='negotiation'; select count(*) into accepted_count from public.proposals where created_at>=start_at and status='accepted'; select count(*) into rejected_count from public.proposals where created_at>=start_at and status='rejected'; select count(*) into expired_count from public.proposals where created_at>=start_at and status='expired'; decided_count:=accepted_count+rejected_count+expired_count; select coalesce(sum(proposal_value),0) into open_value from public.proposals where created_at>=start_at and status in ('draft','sent','negotiation'); select coalesce(sum(proposal_value),0) into accepted_value from public.proposals where created_at>=start_at and status='accepted'; select count(distinct lead_id) into leads_with_proposal from public.proposals where created_at>=start_at; select count(distinct p.lead_id) into sales_from_proposals from public.proposals p join public.leads l on l.id=p.lead_id where p.created_at>=start_at and l.status='won'; acceptance_rate:=case when decided_count=0 then 0 else round((accepted_count::numeric/decided_count::numeric)*100,2) end; proposal_to_sale_rate:=case when leads_with_proposal=0 then 0 else round((sales_from_proposals::numeric/leads_with_proposal::numeric)*100,2) end; return jsonb_build_object('total',total_count,'open',open_count,'sent',sent_count,'negotiation',negotiation_count,'accepted',accepted_count,'rejected',rejected_count,'expired',expired_count,'open_value',open_value,'accepted_value',accepted_value,'acceptance_rate',acceptance_rate,'leads_with_proposal',leads_with_proposal,'sales_from_proposals',sales_from_proposals,'proposal_to_sale_rate',proposal_to_sale_rate); end; $function$;

CREATE OR REPLACE FUNCTION public.next_deal_code()
RETURNS text LANGUAGE sql SET search_path TO 'public'
AS $function$ select 'NEG-' || lpad(nextval('public.deal_code_seq')::text,4,'0'); $function$;

CREATE OR REPLACE FUNCTION public.apply_deal_business_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if new.commission_percent is not null and new.sale_value is not null then if tg_op='INSERT' or new.commission_value is null then new.commission_value:=round((new.sale_value*new.commission_percent/100.0)::numeric,2); elsif old.commission_percent is distinct from new.commission_percent or old.sale_value is distinct from new.sale_value then new.commission_value:=round((new.sale_value*new.commission_percent/100.0)::numeric,2); end if; end if; if new.commission_received_amount is null then new.commission_received_amount:=0; end if; if coalesce(new.commission_value,0)>0 and new.commission_received_amount>=new.commission_value then new.commission_status:='received'; new.commission_received_amount:=new.commission_value; new.commission_received_at:=coalesce(new.commission_received_at,now()); elsif new.commission_received_amount>0 then new.commission_status:='partial'; new.commission_received_at:=null; else new.commission_status:='pending'; new.commission_received_at:=null; end if; if not new.financing_required then new.financing_status:='not_applicable'; elsif new.financing_status='not_applicable' then new.financing_status:='pending'; end if; if new.status='completed' then new.completed_at:=coalesce(new.completed_at,now()); new.cancelled_at:=null; elsif new.status='cancelled' then new.cancelled_at:=coalesce(new.cancelled_at,now()); new.completed_at:=null; else new.completed_at:=null; new.cancelled_at:=null; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.apply_deal_document_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if new.status in ('received','validated') and old.status is distinct from new.status then new.received_at:=coalesce(new.received_at,now()); end if; if new.status='validated' and old.status is distinct from 'validated' then new.validated_at:=coalesce(new.validated_at,now()); elsif new.status<>'validated' then new.validated_at:=null; end if; if new.status='pending' then new.received_at:=null; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.seed_deal_documents()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin insert into public.deal_documents(deal_id,party,doc_key,label,display_order) values (new.id,'buyer','personal_id','Documento de identificação',10),(new.id,'buyer','cpf','CPF',20),(new.id,'buyer','address','Comprovante de endereço',30),(new.id,'buyer','civil_status','Documento de estado civil',40),(new.id,'buyer','income','Comprovante de renda / financiamento',50),(new.id,'seller','personal_id','Documento de identificação',10),(new.id,'seller','cpf','CPF',20),(new.id,'seller','address','Comprovante de endereço',30),(new.id,'seller','civil_status','Documento de estado civil',40),(new.id,'seller','property_registration','Matrícula atualizada do imóvel',50),(new.id,'seller','property_encumbrances','Certidão / situação de ônus do imóvel',60),(new.id,'seller','municipal_taxes','Situação de IPTU / tributos do imóvel',70),(new.id,'transaction','purchase_contract','Contrato / compromisso de compra e venda',10),(new.id,'transaction','financing','Documentação do financiamento',20),(new.id,'transaction','deed','Escritura',30),(new.id,'transaction','registry','Registro do imóvel',40) on conflict(deal_id,party,doc_key) do nothing; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.log_deal_status_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if tg_op='INSERT' then insert into public.deal_status_history(deal_id,from_status,to_status,changed_by) values(new.id,null,new.status,auth.uid()); elsif old.status is distinct from new.status then insert into public.deal_status_history(deal_id,from_status,to_status,changed_by) values(new.id,old.status,new.status,auth.uid()); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.sync_deal_entities()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_purpose text; begin if new.status<>'cancelled' then update public.leads set status='won',deal_value=new.sale_value,commission_value=new.commission_value,closed_at=coalesce(closed_at,now()),next_action_at=null,next_action_text=null where id=new.lead_id; end if; if new.status='completed' and new.property_id is not null then select purpose into v_purpose from public.properties where id=new.property_id; update public.properties set status=case when v_purpose='rent' then 'rented' else 'sold' end where id=new.property_id; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.admin_create_deal_from_proposal(p_proposal_id uuid)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_proposal public.proposals%rowtype; v_lead public.leads%rowtype; v_deal_id uuid; v_percent numeric; begin if not public.has_permission('deals.manage') then raise exception 'not authorized'; end if; select * into v_proposal from public.proposals where id=p_proposal_id; if not found then raise exception 'proposal not found'; end if; if v_proposal.status<>'accepted' then raise exception 'proposal must be accepted'; end if; select id into v_deal_id from public.deals where proposal_id=p_proposal_id or lead_id=v_proposal.lead_id limit 1; if v_deal_id is not null then return v_deal_id; end if; select * into v_lead from public.leads where id=v_proposal.lead_id; if coalesce(v_proposal.proposal_value,0)>0 and coalesce(v_lead.commission_value,0)>0 then v_percent:=round((v_lead.commission_value/v_proposal.proposal_value)*100.0,4); else v_percent:=null; end if; insert into public.deals(lead_id,proposal_id,property_id,sale_value,commission_percent,commission_value,created_by) values(v_proposal.lead_id,v_proposal.id,v_proposal.property_id,coalesce(v_proposal.proposal_value,v_lead.deal_value),v_percent,v_lead.commission_value,auth.uid()) returning id into v_deal_id; insert into public.lead_notes(lead_id,note,created_by) values(v_proposal.lead_id,'Fechamento aberto a partir da proposta '||coalesce(v_proposal.code,'')||'.',auth.uid()); return v_deal_id; end; $function$;

CREATE OR REPLACE FUNCTION public.admin_deal_metrics(days_back integer DEFAULT 365)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare start_at timestamptz; total_count bigint; in_progress_count bigint; completed_count bigint; overdue_commission_count bigint; sold_value numeric; commission_total numeric; commission_received numeric; commission_receivable numeric; begin if not public.has_permission('deals.view') then raise exception 'not authorized'; end if; start_at:=now()-make_interval(days=>greatest(days_back,1)); select count(*) into total_count from public.deals where created_at>=start_at and status<>'cancelled'; select count(*) into in_progress_count from public.deals where created_at>=start_at and status not in ('completed','cancelled'); select count(*) into completed_count from public.deals where created_at>=start_at and status='completed'; select count(*) into overdue_commission_count from public.deals where created_at>=start_at and status<>'cancelled' and commission_status<>'received' and commission_due_date is not null and commission_due_date<current_date; select coalesce(sum(sale_value),0) into sold_value from public.deals where created_at>=start_at and status<>'cancelled'; select coalesce(sum(commission_value),0) into commission_total from public.deals where created_at>=start_at and status<>'cancelled'; select coalesce(sum(commission_received_amount),0) into commission_received from public.deals where created_at>=start_at and status<>'cancelled'; select coalesce(sum(greatest(coalesce(commission_value,0)-coalesce(commission_received_amount,0),0)),0) into commission_receivable from public.deals where created_at>=start_at and status<>'cancelled'; return jsonb_build_object('total',total_count,'in_progress',in_progress_count,'completed',completed_count,'overdue_commissions',overdue_commission_count,'sold_value',sold_value,'commission_total',commission_total,'commission_received',commission_received,'commission_receivable',commission_receivable); end; $function$;

CREATE OR REPLACE FUNCTION public.apply_property_document_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if new.status in ('received','validated') and old.status is distinct from new.status then new.received_at:=coalesce(new.received_at,now()); end if; if new.status='validated' and old.status is distinct from 'validated' then new.validated_at:=coalesce(new.validated_at,now()); elsif new.status<>'validated' then new.validated_at:=null; end if; if new.status='pending' then new.received_at:=null; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.seed_property_documents()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin insert into public.property_documents(property_id,doc_key,label,display_order) values (new.property_id,'owner_id','Documento de identificação do proprietário',10),(new.property_id,'authorization','Autorização para venda / locação',20),(new.property_id,'registration','Matrícula atualizada do imóvel',30),(new.property_id,'municipal_taxes','IPTU / tributos municipais',40),(new.property_id,'encumbrances','Certidão / situação de ônus',50),(new.property_id,'regularization','Regularidade da construção / averbação',60) on conflict(property_id,doc_key) do nothing; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.seed_property_management()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin insert into public.property_management(property_id,listing_started_at) values(new.id,coalesce(new.published_at::date,new.created_at::date,current_date)) on conflict(property_id) do nothing; if new.sale_price is not null then insert into public.property_price_history(property_id,price_type,old_price,new_price) values(new.id,'sale',null,new.sale_price); end if; if new.rent_price is not null then insert into public.property_price_history(property_id,price_type,old_price,new_price) values(new.id,'rent',null,new.rent_price); end if; insert into public.property_status_history(property_id,from_status,to_status) values(new.id,null,new.status); return new; end; $function$;

CREATE OR REPLACE FUNCTION public.sync_capture_property_management()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if new.converted_property_id is not null then insert into public.property_management(property_id,source_capture_id,owner_name,owner_whatsapp,owner_email,listing_started_at,authorization_status,authorization_signed_at,commission_percent) values(new.converted_property_id,new.id,new.owner_name,new.whatsapp,new.email,coalesce(new.updated_at::date,new.created_at::date,current_date),case when new.status in ('authorized','published') then 'authorized' else 'pending' end,case when new.status in ('authorized','published') then coalesce(new.updated_at::date,current_date) else null end,new.commission_percent) on conflict(property_id) do update set source_capture_id=excluded.source_capture_id,owner_name=coalesce(excluded.owner_name,property_management.owner_name),owner_whatsapp=coalesce(excluded.owner_whatsapp,property_management.owner_whatsapp),owner_email=coalesce(excluded.owner_email,property_management.owner_email),commission_percent=coalesce(excluded.commission_percent,property_management.commission_percent),authorization_status=case when excluded.authorization_status='authorized' then 'authorized' else property_management.authorization_status end,authorization_signed_at=coalesce(excluded.authorization_signed_at,property_management.authorization_signed_at); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.log_property_price_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if old.sale_price is distinct from new.sale_price then insert into public.property_price_history(property_id,price_type,old_price,new_price,changed_by) values(new.id,'sale',old.sale_price,new.sale_price,auth.uid()); end if; if old.rent_price is distinct from new.rent_price then insert into public.property_price_history(property_id,price_type,old_price,new_price,changed_by) values(new.id,'rent',old.rent_price,new.rent_price,auth.uid()); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.log_property_status_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if old.status is distinct from new.status then insert into public.property_status_history(property_id,from_status,to_status,changed_by) values(new.id,old.status,new.status,auth.uid()); end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.refresh_property_documentation_status(p_property_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare pending_count integer; validated_or_na_count integer; total_count integer; begin if not public.has_permission('properties.manage') then raise exception 'not authorized'; end if; select count(*),count(*) filter(where status='pending'),count(*) filter(where status in ('validated','not_applicable')) into total_count,pending_count,validated_or_na_count from public.property_documents where property_id=p_property_id; update public.property_management set documentation_status=case when total_count>0 and validated_or_na_count=total_count then 'complete' when pending_count=total_count then 'pending' else 'partial' end where property_id=p_property_id; end; $function$;

CREATE OR REPLACE FUNCTION public.apply_crm_document_rules()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$ begin if tg_op='INSERT' then if new.status in ('approved','rejected') then new.reviewed_at:=coalesce(new.reviewed_at,now()); new.reviewed_by:=coalesce(new.reviewed_by,auth.uid()); end if; elsif old.status is distinct from new.status then if new.status in ('approved','rejected') then new.reviewed_at:=now(); new.reviewed_by:=auth.uid(); else new.reviewed_at:=null; new.reviewed_by:=null; end if; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.crm_document_mark_checklist_received()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if new.property_document_id is not null then update public.property_documents set status='received' where id=new.property_document_id and status='pending'; end if; if new.capture_document_id is not null then update public.capture_documents set status='received' where id=new.capture_document_id and status='pending'; end if; if new.deal_document_id is not null then update public.deal_documents set status='received' where id=new.deal_document_id and status='pending'; end if; if new.rental_document_id is not null then update public.rental_documents set status='received' where id=new.rental_document_id and status='pending'; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.crm_document_sync_review_to_checklist()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if new.status='approved' and old.status is distinct from new.status then if new.property_document_id is not null then update public.property_documents set status='validated' where id=new.property_document_id and status<>'not_applicable'; end if; if new.deal_document_id is not null then update public.deal_documents set status='validated' where id=new.deal_document_id and status<>'not_applicable'; end if; if new.capture_document_id is not null then update public.capture_documents set status='received' where id=new.capture_document_id and status<>'not_applicable'; end if; if new.rental_document_id is not null then update public.rental_documents set status='validated' where id=new.rental_document_id and status<>'not_applicable'; end if; elsif new.status='rejected' and old.status is distinct from new.status then if new.property_document_id is not null then update public.property_documents set status='received' where id=new.property_document_id and status='validated'; end if; if new.deal_document_id is not null then update public.deal_documents set status='received' where id=new.deal_document_id and status='validated'; end if; if new.rental_document_id is not null then update public.rental_documents set status='received' where id=new.rental_document_id and status='validated'; end if; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.sync_property_documentation_summary()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ declare v_property_id uuid; v_total integer; v_pending integer; v_complete integer; begin if tg_op='DELETE' then v_property_id:=old.property_id; else v_property_id:=new.property_id; end if; select count(*),count(*) filter(where status='pending'),count(*) filter(where status in ('validated','not_applicable')) into v_total,v_pending,v_complete from public.property_documents where property_id=v_property_id; update public.property_management set documentation_status=case when v_total>0 and v_complete=v_total then 'complete' when v_total=0 or v_pending=v_total then 'pending' else 'partial' end where property_id=v_property_id; if tg_op='DELETE' then return old; end if; return new; end; $function$;

CREATE OR REPLACE FUNCTION public.crm_document_restore_checklist_pending()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$ begin if old.property_document_id is not null and not exists(select 1 from public.crm_documents where property_document_id=old.property_document_id) then update public.property_documents set status='pending' where id=old.property_document_id and status='received'; end if; if old.capture_document_id is not null and not exists(select 1 from public.crm_documents where capture_document_id=old.capture_document_id) then update public.capture_documents set status='pending' where id=old.capture_document_id and status='received'; end if; if old.deal_document_id is not null and not exists(select 1 from public.crm_documents where deal_document_id=old.deal_document_id) then update public.deal_documents set status='pending' where id=old.deal_document_id and status='received'; end if; return old; end; $function$;;
